os:
  - linux

language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -y bats

install:
  - go get github.com/mynameismevin/takegur

script:
  - bats tests.sh